# Generated by Django 4.2.1 on 2023-05-31 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phn', models.IntegerField()),
                ('plants', models.CharField(max_length=30)),
            ],
        ),
    ]
